language: cpp
compiler:
  - clang
os:
  - linux
  - osx
env:
  - MAME=mame64
script:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    make -j2 LTO=1 linux_x64_clang && ./$MAME -validate;
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    make -j2 LTO=1 MACOSX_USE_LIBSDL=1 && ./$MAME -validate;
    fi
sudo: required
before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:shahar-evron/qt-backports -y; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get install -y --force-yes libsdl2-dev libsdl2-ttf-dev libasound2-dev libqt4-dev libqt4-dev-bin; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew install sdl2 sdl2_ttf; fi"
branches:
  only:
    - master
after_success:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    zip -r mewui.zip $MAME && curl --ftp-create-dirs -T mewui.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/linux/clang/;
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    zip -r mewui.zip $MAME && curl --ftp-create-dirs -T mewui.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/mac/;
    fi

