language: cpp
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - libasound2-dev
            - libqt4-dev
compiler:
  - clang
os:
  - linux
  - osx
env:
  - TARGET=mewui MAME=mewui64 LDOPTS="-Wl,-no-keep-memory"
  - TARGET=mewui MAME=mewui64 MACOSX_USE_LIBSDL=0 OPTIMIZE=0
  - TARGET=mewui MAME=mewui64 MACOSX_USE_LIBSDL=1 OPTIMIZE=0
matrix:
  exclude:
    - os: linux
      env: TARGET=mewui MAME=mewui64 MACOSX_USE_LIBSDL=0 OPTIMIZE=0
    - os: linux
      env: TARGET=mewui MAME=mewui64 MACOSX_USE_LIBSDL=1 OPTIMIZE=0
    - os: osx
      env: TARGET=mewui MAME=mewui64 LDOPTS="-Wl,-no-keep-memory"
script:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    make -j2 OVERRIDE_CXX="clang++-3.6" OVERRIDE_CC="clang-3.6";
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    make -j2;
    fi
sudo: false
install:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    wget https://www.libsdl.org/release/SDL2-2.0.3.tar.gz -O ~/SDL2.tar.gz &&
    tar -xzvf ~/SDL2.tar.gz -C ~/ &&
    mkdir ~/sdl-build &&
    cd ~/sdl-build &&
    ~/SDL2-2.0.3/configure --prefix=$HOME/SDL2 &&
    make &&
    make install &&
    export PATH=$PATH:$HOME/SDL2/bin:$HOME/SDL2/include:$HOME/SDL2/lib &&
    cd ~/build/dankan1890/mewui;
    fi
before_install:
  - "if [ $TRAVIS_OS_NAME == 'osx' ]; then brew update; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 1 ]; then brew install sdl2 sdl2_ttf; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then curl -o SDL2-2.0.3.dmg 'https://www.libsdl.org/release/SDL2-2.0.3.dmg'; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then hdiutil attach SDL2-2.0.3.dmg; fi"
  - "if [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then sudo cp -R /Volumes/SDL2/SDL2.framework /Library/Frameworks/; fi"
branches:
  only:
    - master
after_success:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    echo $TRAVIS_COMMIT &&
    echo $TRAVIS_COMMIT > commit.txt &&
    zip -9 -r mewui64-linux.zip mewui64 docs/ hash/ hlsl/ nl_examples/ samples/ &&
    curl --ftp-create-dirs -T "{mewui64-linux.zip,commit.txt}" -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/tmp/Linux/ &&
    curl --ftp-create-dirs ftp://ftp.mewui.altervista.org/ -Q 'RNFR tmp/Linux/commit.txt' -Q 'RNTO upload/Linux/commit.txt' -u $FTP_USER:$FTP_PASSWORD &&
    curl --ftp-create-dirs ftp://ftp.mewui.altervista.org/ -Q 'RNFR tmp/Linux/mewui64-linux.zip' -Q 'RNTO upload/Linux/mewui64-linux.zip' -u $FTP_USER:$FTP_PASSWORD;
    elif [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 1 ]; then
    echo $TRAVIS_COMMIT &&
    echo $TRAVIS_COMMIT > commit.txt &&
    zip -9 -r mewui64-mac-sdllib.zip mewui64 docs/ hash/ hlsl/ nl_examples/ samples/ &&
    curl --ftp-create-dirs -T "{mewui64-mac-sdllib.zip,commit.txt}" -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/tmp/Mac-Lib/ &&
    curl --ftp-create-dirs ftp://ftp.mewui.altervista.org/ -Q 'RNFR tmp/Mac-Lib/commit.txt' -Q 'RNTO upload/Mac-Lib/commit.txt' -u $FTP_USER:$FTP_PASSWORD &&
    curl --ftp-create-dirs ftp://ftp.mewui.altervista.org/ -Q 'RNFR tmp/Mac-Lib/mewui64-mac-sdllib.zip' -Q 'RNTO upload/Mac-Lib/mewui64-mac-sdllib.zip' -u $FTP_USER:$FTP_PASSWORD;
    elif [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then
    echo $TRAVIS_COMMIT &&
    echo $TRAVIS_COMMIT > commit.txt &&
    zip -9 -r mewui64-mac-sdlframework.zip mewui64 docs/ hash/ hlsl/ nl_examples/ samples/ &&
    curl --ftp-create-dirs -T "{mewui64-mac-sdlframework.zip,commit.txt}" -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/tmp/Mac-Framework/ &&
    curl --ftp-create-dirs ftp://ftp.mewui.altervista.org/ -Q 'RNFR tmp/Mac-Framework/commit.txt' -Q 'RNTO upload/Mac-Framework/commit.txt' -u $FTP_USER:$FTP_PASSWORD &&
    curl --ftp-create-dirs ftp://ftp.mewui.altervista.org/ -Q 'RNFR tmp/Mac-Framework/mewui64-mac-sdlframework.zip' -Q 'RNTO upload/Mac-Framework/mewui64-mac-sdlframework.zip' -u $FTP_USER:$FTP_PASSWORD;
    fi

