language: cpp
compiler:
  - clang
os:
  - linux
  - osx
env:
  - MAME=mame64 LDOPTS="-Wl,-no-keep-memory"
  - MAME=mame64 MACOSX_USE_LIBSDL=0 OPTIMIZE=0
  - MAME=mame64 MACOSX_USE_LIBSDL=1 OPTIMIZE=0
matrix:
  exclude:
    - os: linux
      env: MAME=mame64 MACOSX_USE_LIBSDL=0 OPTIMIZE=0
    - os: linux
      env: MAME=mame64 MACOSX_USE_LIBSDL=1 OPTIMIZE=0
    - os: osx
      env: MAME=mame64 LDOPTS="-Wl,-no-keep-memory"
script:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    make -j2 linux_x64_clang && ./$MAME -validate;
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    make -j2 && ./$MAME -validate;
    fi
sudo: required
before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:shahar-evron/qt-backports -y; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get install -y --force-yes libsdl2-dev libsdl2-ttf-dev libasound2-dev libqt4-dev libqt4-dev-bin; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ] && [ $MACOSX_USE_LIBSDL == 1 ]; then brew install sdl2 sdl2_ttf; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then curl -o SDL2-2.0.3.dmg 'https://www.libsdl.org/release/SDL2-2.0.3.dmg'; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then hdiutil attach SDL2-2.0.3.dmg; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then sudo cp -R /Volumes/SDL2/SDL2.framework /Library/Frameworks/; fi"
branches:
  only:
    - master
after_success:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    echo $TRAVIS_COMMIT && echo $TRAVIS_COMMIT > commit.txt && mv $MAME mewui64 && zip -9 -r mewui64-linux.zip mewui64 docs/ hash/ hlsl/ web/ nl_examples/ samples/ && curl --ftp-create-dirs -T "{mewui64-linux.zip,commit.txt}" -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/Linux/;
    elif [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 1 ]; then
    mv $MAME mewui64 && zip -9 -r mewui64-mac-sdllib.zip mewui64 docs/ hash/ hlsl/ web/ nl_examples/ samples/ && curl --ftp-create-dirs -T mewui64-mac-sdllib.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/Mac/;
    elif [ $TRAVIS_OS_NAME == 'osx' ] && [ $MACOSX_USE_LIBSDL == 0 ]; then
    mv $MAME mewui64 && zip -9 -r mewui64-mac-sdlframework.zip mewui64 docs/ hash/ hlsl/ web/ nl_examples/ samples/ && curl --ftp-create-dirs -T mewui64-mac-sdlframework.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/Mac/;
    fi

