language: cpp
compiler:
  - clang
os:
  - linux
  - osx
env:
  - MAME=mame64 LDOPTS="-Wl,-no-keep-memory" MACOSX_USE_LIBSDL=0
  - MAME=mame64 LDOPTS="-Wl,-no-keep-memory" MACOSX_USE_LIBSDL=1
script:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    unset MACOSX_USE_LIBSDL && make -j2 linux_x64_clang && ./$MAME -validate;
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    unset LDOPTS && make -j2 OPTIMIZE=0 && ./$MAME -validate;
    fi
sudo: required
before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo add-apt-repository ppa:shahar-evron/qt-backports -y; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get install -y --force-yes libsdl2-dev libsdl2-ttf-dev libasound2-dev libqt4-dev libqt4-dev-bin; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew install sdl2 sdl2_ttf; fi"
branches:
  only:
    - master
after_success:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then
    mv $MAME mewui64 && zip -r mewui64-linux.zip mewui64 docs/ hash/ hlsl/ web/ nl_examples/ samples/ && curl --ftp-create-dirs -T mewui64-linux.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/Linux/;
    elif [ $TRAVIS_OS_NAME == 'osx' ]; then
    mv $MAME mewui64 && zip -r mewui64-mac.zip mewui64 docs/ hash/ hlsl/ web/ nl_examples/ samples/ && curl --ftp-create-dirs -T mewui64-mac.zip -u $FTP_USER:$FTP_PASSWORD ftp://ftp.mewui.altervista.org/upload/Mac/;
    fi

